add step to use as check in repository rules

diff --git a/.github/workflows/pr-github-checks.yml b/.github/workflows/pr-github-checks.yml
--- a/.github/workflows/pr-github-checks.yml
+++ b/.github/workflows/pr-github-checks.yml
@@ -10,9 +10,48 @@ on:
       - reopened
       - edited
       - synchronize
+      - labeled
+      - milestoned
   workflow_dispatch:
 
 jobs:
+  pr-milestone-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for milestone
+        env:
+          MILESTONE: ${{ toJSON(github.event.pull_request.milestone) }}
+        run: |
+          echo "${MILESTONE}" | jq -e '.!=null' || (echo "Milestone is not set"; exit 1)
+
+  pr-label-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for area label
+        if: always()
+        run: |
+          gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
+          grep -q '^area/' || (echo "area label missing"; exit 1)
+        env:
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Check for kind label
+        if: always()
+        run: |
+          gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
+          grep -q '^kind/' || (echo "kind label missing"; exit 1)
+        env:
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Check if kind label matches pr title prefix
+        run: |
+          kind_label=$( gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | grep '^kind/')
+          kind_label_to_pr_title_prefix='{"kind/bug":"fix","kind/feature":"feat","kind/docs":"docs","kind/chore":"chore","kind/flaky-test":"test","kind/missing-test":"test","kind/failing-test":"test","kind/deps":"deps"}'
+          prefix=$(echo $kind_label_to_pr_title_prefix | jq -r ".\"$kind_label\"")
+          echo "${{ github.event.pull_request.title }}" | grep '^'$prefix || (echo "PR title should start with $prefix"; exit 1)
+        env:
+          GH_TOKEN: ${{ github.token }}
+
   pr-title-check:
     runs-on: ubuntu-latest
     steps:
@@ -30,3 +69,10 @@ jobs:
             test
           requireScope: false
           subjectPattern: ^([A-Z].*[^.]|bump .*)$
+
+  PR-Github-Checks-Success:
+    runs-on: ubuntu-latest
+    needs: [pr-milestone-check, pr-label-check, pr-title-check]
+    steps:
+      - name: PR Github Checks Success
+        run: echo "PR Github Checks Success"
