chore: Fix label check

diff --git a/.github/workflows/pr-github-checks.yml b/.github/workflows/pr-github-checks.yml
--- a/.github/workflows/pr-github-checks.yml
+++ b/.github/workflows/pr-github-checks.yml
@@ -22,7 +22,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^area/' || (echo "area label missing"; exit 1)
+          grep -q '^area\/' || (echo "area label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -30,7 +30,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^kind/' || (echo "kind label missing"; exit 1)
+          grep -q '^kind\/' || (echo "kind label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -47,7 +47,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^do-not-merge/$' && (echo "do-not-merge label detected -> preventing merge by failing the job"; exit 1)
+          grep -q '^do-not-merge\/' && (echo "do-not-merge label detected -> preventing merge by failing the job"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
